### PR TITLE
Update colors, make glyph views independent, support dark mode

### PR DESCRIPTION
**Pull request by ryanbugden**
Changes were made with both `ShowMouseCoordinates` and `ShowCharacterInfo` in mind.

### CODE REVIEW

**Comment by ryanbugden** [comment]
Not sure how backwards-compatible some of these changes will be. Anything cutting-edge, I put in version-conditional statements. Should be fine for most.

e.g.
`glyph.getParent()` (deprecated) → `glyph.font`

**Comment by djrrb** [comment]
FWIW I’m getting this on RF 4.3

```
********************
Installing 'Show Character Info' report:
  Traceback (most recent call last):
      File "showCharacterInfo.py", line 10, in <module>
    ImportError: cannot import name 'appearanceColorKey' from 'mojo.UI' (/Applications/RoboFont.app/Contents/Resources/lib/python3.7/mojo/UI.py)
  
********************
```

**Comment by ryanbugden** [comment]
Oh woops I forgot to make the import version-conditional. Will update

**Comment by ryanbugden** [comment]
Tested on 4.3 and it seems good-to-go now.

**Comment by djrrb** [comment]
Looks good to me, thanks so much!!!

**Pull request merged**
