### PR TITLE
remove redundant extension + fresh new build

### PR DESCRIPTION
**Pull request by roberto-arista**

### CODE REVIEW

**Comment by roberto-arista** [comment]
actually it was a mistake, I thought I was working on my own fork of the repository 🤣

**Comment by roberto-arista** [comment]
I've already rolled it back, but you can keep it if you like

**Comment by djrrb** [comment]
haha it is a testament to how much i trust your commits! 😁

**Comment by roberto-arista** [comment]
☺️

**Comment by roberto-arista** [comment]
It does not break anything, it is only a bit more lenient towards dark mode. The idea comes from this discussion: https://robofontcommunity.slack.com/archives/C03DUNMBVDZ/p1661977764140999

**Pull request merged**
