### PR TITLE
Update OverlayUFOs to RF4

### PR DESCRIPTION
**Pull request by roberto-arista**
Since I changed the folder structure, I assume we have to update the Mechanic register, right?

### CODE REVIEW

**Comment by djrrb** [comment]
Haha probably! I forget how to do this, but I will look into that before accepting the PR (after I send out my Font of the Month.)

Thanks for this!

**Comment by roberto-arista** [comment]
any luck with this?

**Comment by roberto-arista** [comment]
They are now compatible!

**Comment by djrrb** [comment]
You rock @roberto-arista...thanks so much!

**Comment by roberto-arista** [comment]
🎉

**Pull request merged**
